POST http://localhost:3333/videos
Content-type: application/json

{
    "title": "PEDRO",
    "description": "marta",
    "duration": 100
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/
Content-type: application/json

{
    "title": "Thiago Mula",
    "description": "marta",
    "duration": 80
}