POST http://localhost:3333/videos
Content-type: application/json

{
    "title": "PEDRO",
    "description": "marta",
    "duration": 100
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/
Content-type: application/json

{
    "title": "Thiago Mula",
    "description": "marta",
    "duration": 80
}

###

DELETE  http://localhost:3333/videos/86010de1-6fe7-4c78-8bbe-8a0c6df121ba
